stages:
  - build
  - test
  - deploy

cmake-build:
  image: ubuntu:bionic
  stage: build
  script:
  - apt update && apt install -y gcc cmake build-essential cmake git-core lcov ggcov libboost-all-dev
  - mkdir build && cd build
  - cmake ..
  - make
  artifacts:
    paths:
    - bin/*

doxygen-generate:
  image: alpine:lastest
  stage: build
  script:
  - apt update && apt install -y doxygen graphviz
  - doxygen
  artifacts:
    paths:
    - docs/html/*
  only:
    - master

gtest-test:
  image: alpine:lastest
  stage: test
  dependencies:
    - cmake-build
  script:
  - ./bin/computing-fundamentals-cpp-unittests

pages:
  image: alpine:lastest
  stage: deploy
  dependencies:
    - doxygen-generate
  script:
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
