stages:
  - build
  - test
  - deploy

cmake-build:
  image: ubuntu:bionic
  stage: build
  coverage: '/Overall coverage rate:\D+lines.+:\s(\d+[.]?\d?)%/'
  script:
  - apt update && apt install -y gcc cmake lcov ggcov build-essential libboost-all-dev git-core
  - mkdir build && cd build
  - cmake ..
  - make computing-fundamentals-cpp computing-fundamentals-cpp-coverage
  - mv coverage/ ..
  artifacts:
    paths:
    - bin/*
    - coverage/*

doxygen-generate:
  image: alpine:latest
  stage: build
  script:
  - apk add --no-cache doxygen graphviz
  - doxygen
  artifacts:
    paths:
    - docs/html/*
  only:
    - master

gtest-test:
  image: ubuntu:bionic
  stage: test
  dependencies:
    - cmake-build
  script:
  - ./bin/computing-fundamentals-cpp-unittests

pages:
  image: alpine:latest
  stage: deploy
  dependencies:
    - cmake-build
    - doxygen-generate
  script:
    - mv docs/html/ public/
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public
  only:
    - master
