image: gcc

before_script:  
  - apt-get update && apt-get -y install cmake build-essential cmake git-core lcov ggcov libboost-all-dev

stages:
  - build
  - test

cmake-build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  artifacts:
    paths:
    - bin/*

gtest-test:
  stage: test
  dependencies:
    - cmake-build
  script:
  - ./bin/computing-fundamentals-cpp-unittests