image: gcc

before_script:  
  - apt-get update && apt-get -y install cmake

stages:
  - build
  - test
  - deploy

cmake-build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - make  
  artifacts:
    paths:
     - bin/*
     - test/*

gtest-test:
  stage: test
  dependencies:
    - cmake-build
#   coverage: '/coverage line-rate.*?([0-9]{1,3})%/'
  script:
  - ./computing_fundamentals
#   - mvn cobertura:dump-datafile -B
#   artifacts:
#     paths:
#     - target/site/cobertura/*
