image: ubuntu:bionic

before_script:  
  - apt-get update && apt-get -y install gcc cmake build-essential cmake git-core lcov ggcov libboost-all-dev doxygen

stages:
  - build
  - test
  - deploy

cmake-build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  artifacts:
    paths:
    - bin/*

gtest-test:
  stage: test
  dependencies:
    - cmake-build
  script:
  - ./bin/computing-fundamentals-cpp-unittests

doxygen-generate:
  stage: deploy
  script:
  - doxygen
  artifacts:
    paths:
    - docs/html/*

pages:
  stage: deploy
  dependencies:
    - doxygen-generate
  script:
    - mv docs/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
