language: cpp

compiler:
  - gcc

install:
  - |
    CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake ..)

script:
  make
  ./computing_fundamentals
