name: C++ Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up C++ build environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y g++
      - name: Build C++ app
        run: make
